### ISSUE TITLE
Pulseaudio: crash if two file have different samplerate

### ISSUE THREAD

**Issue by pingplug** [Alexey-Yakovenko/deadbeef#1358]
Arch Linux 64bit, deadbeef-git in the AUR
deadbeef will get a SIGABRT if the samplerate of two file different

it seems that pulse_setformat() called twice
and pulse_stop() called twice(21a4bda93772f447598594967d346f8be9371458)
then pulse_free() called twice(c43f4189849b1e94040abc63b3e2b1f27afbde91)

**Comment by Alexey-Yakovenko** [comment]
@pingplug  Your fix caused more issues / regressions than it fixed, and I have to back it out. Please report a new bug with description how to reproduce it, if it still happens for you.

**Comment by Alexey-Yakovenko** [comment]
p.s. I couldn't reproduce your original bug report. Please attach backtrace if the bug happens again for you. SIGABRT is not even a normal crash. It's from an assert usually.

**Comment by pingplug** [comment]
commit 41b90a9e57ee25e851512a36efd23391aff63bb2 fix this problem
pulse_setformat() only called once after that commit

**Comment by Alexey-Yakovenko** [comment]
Reproduced by accident with the following backtrace:

```
Assertion 'pa_atomic_load(&(s)->_ref) >= 1' failed at pulse/stream.c:319, function pa_stream_unref(). Aborting.

Program received signal SIGABRT, Aborted.
[Switching to Thread 0xa91cbb40 (LWP 12611)]
0xb7fdd424 in __kernel_vsyscall ()
(gdb) bt
#0  0xb7fdd424 in __kernel_vsyscall ()
#1  0xb7dfce0f in __GI_raise (sig=6)
    at ../nptl/sysdeps/unix/sysv/linux/raise.c:64
#2  0xb7e00455 in __GI_abort () at abort.c:91
#3  0xb55874ab in pa_stream_unref () from /usr/lib/i386-linux-gnu/libpulse.so.0
#4  0xb5587549 in ?? () from /usr/lib/i386-linux-gnu/libpulse.so.0
#5  0xb558730f in pa_stream_unref () from /usr/lib/i386-linux-gnu/libpulse.so.0
#6  0xb55ab425 in pa_simple_free ()
   from /usr/lib/i386-linux-gnu/libpulse-simple.so.0
#7  0xb561888f in pulse_free () at pulse.c:231
#8  0xb5618b0e in pulse_thread (context=0x0) at pulse.c:319
#9  0xb7f7ed4c in start_thread (arg=0xa91cbb40) at pthread_create.c:308
#10 0xb7ebdb8e in clone () at ../sysdeps/unix/sysv/linux/i386/clone.S:130```

**Comment by Alexey-Yakovenko** [comment]
another different callstack

```
Program received signal SIGSEGV, Segmentation fault.
0x6e2f656d in ?? ()
(gdb) bt
#0  0x6e2f656d in ?? ()
#1  0xb552f5be in ?? () from /usr/lib/i386-linux-gnu/libpulsecommon-1.1.so
#2  0xb552fb91 in pa_socket_client_new_sockaddr ()
   from /usr/lib/i386-linux-gnu/libpulsecommon-1.1.so
#3  0xb552fd89 in pa_socket_client_new_unix ()
   from /usr/lib/i386-linux-gnu/libpulsecommon-1.1.so
#4  0xb5530f28 in pa_socket_client_new_string ()
   from /usr/lib/i386-linux-gnu/libpulsecommon-1.1.so
#5  0xb55685f9 in ?? () from /usr/lib/i386-linux-gnu/libpulse.so.0
#6  0xb5569117 in pa_context_connect ()
   from /usr/lib/i386-linux-gnu/libpulse.so.0
#7  0xb55ab608 in pa_simple_new ()
   from /usr/lib/i386-linux-gnu/libpulse-simple.so.0
#8  0xb5618cf2 in pulse_set_spec (fmt=<optimized out>) at pulse.c:150
#9  0xb5618f7d in pulse_setformat (fmt=0xbfffcd28) at pulse.c:196
#10 pulse_setformat (fmt=0xbfffcd28) at pulse.c:181
#11 0x080591fd in streamer_set_output_format () at streamer.c:2294
#12 0x0805d0ed in streamer_ok_to_read (len=-1) at streamer.c:2718
#13 0xb7b81395 in draw_column_data (listview=0x83a02f0, cr=0xb754e500, 
    it=0x81c3150, idx=0, column=1, iter=0, x=100, y=0, width=50, height=23)
    at plcommon.c:359
```
