### ISSUE TITLE
100% CPU when stopped by "stop after current track"

### ISSUE THREAD

**Issue by pingplug** [Alexey-Yakovenko/deadbeef#1784]
### Expected behavior
stop and use 0% CPU

### Actual behavior
icon shows buffering and use 100% CPU

### Steps to reproduce the behavior
select "stop after current track"
play something
wait for it stop

**Comment by pingplug** [comment]
OS: Arch Linux 64bit
Version: latest git build

**Comment by Alexey-Yakovenko** [comment]
note: "latest git build" is not really useful. would be nice if you post a specific revision, as "latest" changes all the time, often multiple times a day, and there are multiple branches.

**Comment by Lithopsian** [comment]
Is this still happening in a slightly different case? When playback ends naturally at the end of a playlist, I'm seeing 100% cpu.  It doesn't happen if "stop after current track" is set. It goes back to normal when I start to play again.

**Comment by kuba160** [comment]
I can confirm with looping disabled.
Log message: `streamer: streamer_read has starved. The current output plugin might be broken`
It loops at fast rate.

Backtrace:
```
(gdb) thread apply all bt

Thread 14 (Thread 0x7fffc6ffd700 (LWP 14095)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:143
#1  0x00007fffe35e2278 in pa_threaded_mainloop_wait () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
#2  0x00007fffe3801cb2 in pa_simple_write () from /usr/lib/x86_64-linux-gnu/libpulse-simple.so.0
#3  0x00007fffe3a05fa4 in pulse_thread (context=<optimized out>) at pulse.c:315
#4  0x00007ffff76bb494 in start_thread (arg=0x7fffc6ffd700) at pthread_create.c:333
#5  0x00007ffff73fdaff in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 13 (Thread 0x7fffc77fe700 (LWP 14094)):
#0  0x00007ffff73f46ad in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007fffe35e1c91 in ?? () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
#2  0x00007fffe35d34a1 in pa_mainloop_poll () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
#3  0x00007fffe35d3b3e in pa_mainloop_iterate () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
#4  0x00007fffe35d3bf0 in pa_mainloop_run () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
#5  0x00007fffe35e1bd9 in ?? () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
#6  0x00007fffe33812c8 in ?? () from /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-10.0.so
#7  0x00007ffff76bb494 in start_thread (arg=0x7fffc77fe700) at pthread_create.c:333
#8  0x00007ffff73fdaff in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 11 (Thread 0x7fffcf7fe700 (LWP 14092)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007ffff6c56183 in loading_thread (none=<optimized out>) at coverart.c:405
#2  0x00007ffff76bb494 in start_thread (arg=0x7fffcf7fe700) at pthread_create.c:333
#3  0x00007ffff73fdaff in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 10 (Thread 0x7fffcffff700 (LWP 14091)):
#0  0x00007ffff73f46ad in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007ffff47499f6 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff4749d82 in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff4d31656 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#4  0x00007ffff47713d5 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff76bb494 in start_thread (arg=0x7fffcffff700) at pthread_create.c:333
#6  0x00007ffff73fdaff in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 9 (Thread 0x7fffdce79700 (LWP 14090)):
#0  0x00007ffff73f46ad in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007ffff47499f6 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff4749b0c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff4749b51 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007ffff47713d5 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff76bb494 in start_thread (arg=0x7fffdce79700) at pthread_create.c:333
#6  0x00007ffff73fdaff in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 8 (Thread 0x7fffdd67a700 (LWP 14089)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x000055555559d18b in cond_wait (c=93824995570432, m=93824995570384) at threading_pthread.c:217
#2  0x000055555559bec7 in messagepump_wait () at messagepump.c:115
#3  0x00005555555899f4 in player_mainloop () at main.c:709
#4  0x0000555555589b99 in mainloop_thread (ctx=<optimized out>) at main.c:834
#5  0x00007ffff76bb494 in start_thread (arg=0x7fffdd67a700) at pthread_create.c:333
#6  0x00007ffff73fdaff in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 7 (Thread 0x7fffebcc5700 (LWP 14088)):
---Type <return> to continue, or q <return> to quit---
#0  0x00007ffff73f63f3 in select () at ../sysdeps/unix/syscall-template.S:84
#1  0x00005555555896dd in server_loop (ctx=<optimized out>) at main.c:586
#2  0x00007ffff76bb494 in start_thread (arg=0x7fffebcc5700) at pthread_create.c:333
#3  0x00007ffff73fdaff in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 6 (Thread 0x7fffdde7b700 (LWP 14087)):
#0  0x00007ffff7ffac40 in gettimeofday ()
#1  0x0000555555598522 in streamer_thread (ctx=<optimized out>) at streamer.c:1331
#2  0x00007ffff76bb494 in start_thread (arg=0x7fffdde7b700) at pthread_create.c:333
#3  0x00007ffff73fdaff in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 5 (Thread 0x7fffde67c700 (LWP 14086)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x000055555559d18b in cond_wait (c=93824996183456, m=93824996183408) at threading_pthread.c:217
#2  0x00007fffe9035824 in lfm_thread (ctx=<optimized out>) at lastfm.c:734
#3  0x00007ffff76bb494 in start_thread (arg=0x7fffde67c700) at pthread_create.c:333
#4  0x00007ffff73fdaff in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 4 (Thread 0x7fffdee7d700 (LWP 14085)):
#0  0x00007ffff73cd24d in nanosleep () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007ffff73f6bb4 in usleep (useconds=useconds@entry=200000) at ../sysdeps/posix/usleep.c:32
#2  0x00007fffe950ff5f in hotkeys_event_loop (unused=<optimized out>) at hotkeys.c:498
#3  0x00007ffff76bb494 in start_thread (arg=0x7fffdee7d700) at pthread_create.c:333
#4  0x00007ffff73fdaff in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 3 (Thread 0x7fffdf67e700 (LWP 14084)):
#0  pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
#1  0x00007fffec5cd7af in cache_cleaner_thread (none=<optimized out>) at cache.c:182
#2  0x00007ffff76bb494 in start_thread (arg=0x7fffdf67e700) at pthread_create.c:333
#3  0x00007ffff73fdaff in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 2 (Thread 0x7fffdfe7f700 (LWP 14083)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007fffec5cd0f1 in fetcher_thread (none=<optimized out>) at artwork.c:1838
#2  0x00007ffff76bb494 in start_thread (arg=0x7fffdfe7f700) at pthread_create.c:333
#3  0x00007ffff73fdaff in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 1 (Thread 0x7ffff7fb6e80 (LWP 14079)):
#0  0x00007ffff73f46ad in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007ffff47499f6 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff4749b0c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff4d0572d in g_application_run () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#4  0x00007ffff6c280fe in gtkui_thread (ctx=ctx@entry=0x0) at gtkui.c:1381
#5  0x00007ffff6c2818c in gtkui_start () at gtkui.c:1510
#6  0x0000555555588265 in main (argc=<optimized out>, argv=<optimized out>) at main.c:1182
```

**Comment by Alexey-Yakovenko** [comment]
hmm.. weird enough I can't reproduce this with 3 output plugins.

**Comment by Lithopsian** [comment]
I double-checked and I wasn't building output plugins because of missing libraries. With a new alsa.so the error still seems to be there, but the 100% CPU goes away after a few seconds.

**Comment by kuba160** [comment]
I was able to reproduce it on my laptop (Debian stretch). I'm using b284c9eb233223c9609eaf3c3ee9f92beff16561 (latest until time of writing) with PulseAudio output plugin.
Steps to reproduce:
1. Disable looping (Playback/Looping/Don't loop).
2. Turn last song on playlist.
(2.5 Seek to last 10 seconds.)
3. CPU usage raises 5 seconds before song ends.
4. After song finishes, usage does not sink.

Backtrace: 
```
(gdb) thread apply all bt

Thread 19 (Thread 0x7fffe4d0f700 (LWP 21059)):
#0  0x00007ffff73f46ad in poll () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007fffe9d9cc91 in ?? () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
#2  0x00007fffe9d8e4a1 in pa_mainloop_poll ()
   from /usr/lib/x86_64-linux-gnu/libpulse.so.0
#3  0x00007fffe9d8eb3e in pa_mainloop_iterate ()
   from /usr/lib/x86_64-linux-gnu/libpulse.so.0
#4  0x00007fffe9d8ebf0 in pa_mainloop_run ()
   from /usr/lib/x86_64-linux-gnu/libpulse.so.0
#5  0x00007fffe9d9cbd9 in ?? () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
#6  0x00007fffe9b3c2c8 in ?? ()
   from /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-10.0.so
#7  0x00007ffff76bb494 in start_thread ()
   from /lib/x86_64-linux-gnu/libpthread.so.0
#8  0x00007ffff73fdaff in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 17 (Thread 0x7fffcb7fe700 (LWP 21057)):
#0  0x00007ffff76c1147 in pthread_cond_wait@@GLIBC_2.3.2 ()
   from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007fffe9d9d278 in pa_threaded_mainloop_wait ()
   from /usr/lib/x86_64-linux-gnu/libpulse.so.0
#2  0x00007fffe9fbccb2 in pa_simple_write ()
---Type <return> to continue, or q <return> to quit---
   from /usr/lib/x86_64-linux-gnu/libpulse-simple.so.0
#3  0x00007fffea1c0fa4 in pulse_thread (context=<optimized out>) at pulse.c:315
#4  0x00007ffff76bb494 in start_thread ()
   from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007ffff73fdaff in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 9 (Thread 0x7fffcaffd700 (LWP 21049)):
#0  0x00007ffff73f46ad in poll () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff48ca9f6 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff48cad82 in g_main_loop_run ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff4eb2656 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#4  0x00007ffff48f23d5 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff76bb494 in start_thread ()
   from /lib/x86_64-linux-gnu/libpthread.so.0
#6  0x00007ffff73fdaff in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 7 (Thread 0x7fffcbfff700 (LWP 21047)):
#0  0x00007ffff73f46ad in poll () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff48ca9f6 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff48cab0c in g_main_context_iteration ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff48cab51 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007ffff48f23d5 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff76bb494 in start_thread ()
   from /lib/x86_64-linux-gnu/libpthread.so.0
#6  0x00007ffff73fdaff in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 5 (Thread 0x7fffe5510700 (LWP 21045)):
#0  0x00007ffff76c115f in pthread_cond_wait@@GLIBC_2.3.2 ()
   from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x000055555559d19b in cond_wait (c=93824995570432, m=93824995570384)
    at threading_pthread.c:217
#2  0x000055555559bed7 in messagepump_wait () at messagepump.c:115
#3  0x00005555555899f4 in player_mainloop () at main.c:709
#4  0x0000555555589b99 in mainloop_thread (ctx=<optimized out>) at main.c:834
#5  0x00007ffff76bb494 in start_thread ()
   from /lib/x86_64-linux-gnu/libpthread.so.0
#6  0x00007ffff73fdaff in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 4 (Thread 0x7fffecf4e700 (LWP 21044)):
#0  0x00007ffff73f63f3 in select () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00005555555896dd in server_loop (ctx=<optimized out>) at main.c:586
#2  0x00007ffff76bb494 in start_thread ()
   from /lib/x86_64-linux-gnu/libpthread.so.0
#3  0x00007ffff73fdaff in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 3 (Thread 0x7fffe5d11700 (LWP 21043)):
#0  0x00007ffff7ffa947 in ?? ()
#1  0x00007ffff7ffad56 in gettimeofday ()
#2  0x0000555555598522 in streamer_thread (ctx=<optimized out>)
    at streamer.c:1331
#3  0x00007ffff76bb494 in start_thread ()
   from /lib/x86_64-linux-gnu/libpthread.so.0
#4  0x00007ffff73fdaff in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 2 (Thread 0x7fffe6512700 (LWP 21042)):
#0  0x00007ffff73cd24d in nanosleep () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff73f6bb4 in usleep () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007fffeb011f5f in hotkeys_event_loop (unused=<optimized out>)
    at hotkeys.c:498
#3  0x00007ffff76bb494 in start_thread ()
   from /lib/x86_64-linux-gnu/libpthread.so.0
#4  0x00007ffff73fdaff in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 1 (Thread 0x7ffff7fb3e80 (LWP 21038)):
#0  0x00007ffff73f46ad in poll () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff48ca9f6 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff48cab0c in g_main_context_iteration ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff4e8672d in g_application_run ()
   from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#4  0x00007ffff6da90fe in gtkui_thread (ctx=ctx@entry=0x0) at gtkui.c:1381
#5  0x00007ffff6da918c in gtkui_start () at gtkui.c:1510
#6  0x0000555555588265 in main (argc=<optimized out>, argv=<optimized out>)
    at main.c:1182
```

**Comment by kuba160** [comment]
I managed to catch different one. This thread is using cpu.
```
Thread 3 (Thread 0x7fffe5d11700 (LWP 21544)):
#0  0x00007ffff76bf1c0 in __pthread_mutex_unlock_usercnt ()
   from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x000055555559d0c6 in mutex_unlock (_mtx=<optimized out>)
    at threading_pthread.c:182
#2  0x00005555555aa053 in handler_pop (h=0x555555881080, 
    id=id@entry=0x7fffe5d10f04, ctx=ctx@entry=0x7fffe5d10f10, 
    p1=p1@entry=0x7fffe5d10f08, p2=p2@entry=0x7fffe5d10f0c) at handler.c:126
#3  0x0000555555598542 in streamer_thread (ctx=<optimized out>)
    at streamer.c:1336
#4  0x00007ffff76bb494 in start_thread ()
   from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007ffff73fdaff in clone () from /lib/x86_64-linux-gnu/libc.so.6
```

**Comment by Alexey-Yakovenko** [comment]
@kuba160 what about reproduction rate? does it happen every time?

(I know which thread is causing CPU load, but I need to be able to reproduce the problem to find out why)

**Comment by kuba160** [comment]
@Alexey-Yakovenko It happened every time I did it. However I run it with ALSA plugin, cpu usage raises 5s before song finishes and sinks right after song finishes.
I don't know what's with null output plugin. After I turn song, playback goes like 10x times faster. CPU usage is very high. It reaches nearly 200% after song ends.

**Comment by Alexey-Yakovenko** [comment]
Seems like I nailed it this time. Please re-check.

**Comment by Lithopsian** [comment]
It all looks good here.
