### ISSUE TITLE
Player hangs when pausing (pulseaudio plugin)

### ISSUE THREAD

**Issue by kuba160** [Alexey-Yakovenko/deadbeef#1791]
Player hangs when pausing a song. It becomes unresponsive to any music actions like stopping and changing songs. GUI still works. 

Steps:
1. Start song
2. Press pause
3. Pressing stop or changing song doesn't have any effects.

Backtrace: (Thread 10 has mutex lock)
```
(gdb) thread apply all bt

Thread 14 (Thread 0x7fffbe7fc700 (LWP 10517)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007ffff6c584c3 in loading_thread (none=<optimized out>) at coverart.c:405
#2  0x00007ffff76bb494 in start_thread (arg=0x7fffbe7fc700) at pthread_create.c:333
#3  0x00007ffff73fe93f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 13 (Thread 0x7fffbeffd700 (LWP 10516)):
#0  0x00007ffff73f54ed in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007ffff474c9f6 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff474cd82 in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff4f36656 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#4  0x00007ffff47743d5 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff76bb494 in start_thread (arg=0x7fffbeffd700) at pthread_create.c:333
#6  0x00007ffff73fe93f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 12 (Thread 0x7fffbf7fe700 (LWP 10515)):
#0  0x00007ffff73f54ed in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007ffff474c9f6 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff474cb0c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff474cb51 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007ffff47743d5 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff76bb494 in start_thread (arg=0x7fffbf7fe700) at pthread_create.c:333
#6  0x00007ffff73fe93f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 10 (Thread 0x7fffbffff700 (LWP 10513)):
#0  __lll_lock_wait () at ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
#1  0x00007ffff76bdc06 in __GI___pthread_mutex_lock (mutex=0x555555916ad0)
    at ../nptl/pthread_mutex_lock.c:115
#2  0x000055555559c486 in mutex_lock (_mtx=<optimized out>) at threading_pthread.c:172
#3  0x00007fffeab7b098 in pulse_free () at pulse.c:209
#4  0x00007fffeab7b123 in pulse_pause () at pulse.c:255
#5  0x0000555555589750 in player_mainloop () at main.c:656
#6  0x0000555555589979 in mainloop_thread (ctx=<optimized out>) at main.c:812
#7  0x00007ffff76bb494 in start_thread (arg=0x7fffbffff700) at pthread_create.c:333
#8  0x00007ffff73fe93f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 9 (Thread 0x7fffdcee0700 (LWP 10512)):
#0  0x00007ffff73f7233 in select () at ../sysdeps/unix/syscall-template.S:84
#1  0x00005555555894bd in server_loop (ctx=<optimized out>) at main.c:564
#2  0x00007ffff76bb494 in start_thread (arg=0x7fffdcee0700) at pthread_create.c:333
#3  0x00007ffff73fe93f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 8 (Thread 0x7fffdd6e1700 (LWP 10511)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:143
#1  0x00007fffe3649278 in pa_threaded_mainloop_wait () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
#2  0x00007fffe3868cb2 in pa_simple_write () from /usr/lib/x86_64-linux-gnu/libpulse-simple.so.0
#3  0x00007fffeab7afa4 in pulse_thread (context=<optimized out>) at pulse.c:315
#4  0x00007ffff76bb494 in start_thread (arg=0x7fffdd6e1700) at pthread_create.c:333
#5  0x00007ffff73fe93f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 7 (Thread 0x7fffebcc8700 (LWP 10510)):
#0  0x00007ffff73f54ed in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007fffe3648c91 in ?? () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
---Type <return> to continue, or q <return> to quit---
#2  0x00007fffe363a4a1 in pa_mainloop_poll () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
#3  0x00007fffe363ab3e in pa_mainloop_iterate () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
#4  0x00007fffe363abf0 in pa_mainloop_run () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
#5  0x00007fffe3648bd9 in ?? () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
#6  0x00007fffe33e82c8 in ?? () from /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-10.0.so
#7  0x00007ffff76bb494 in start_thread (arg=0x7fffebcc8700) at pthread_create.c:333
#8  0x00007ffff73fe93f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 6 (Thread 0x7fffddee2700 (LWP 10509)):
#0  0x00007ffff73ce08d in nanosleep () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007ffff73f79f4 in usleep (useconds=useconds@entry=50000) at ../sysdeps/posix/usleep.c:32
#2  0x0000555555597b36 in streamer_thread (ctx=<optimized out>) at streamer.c:1390
#3  0x00007ffff76bb494 in start_thread (arg=0x7fffddee2700) at pthread_create.c:333
#4  0x00007ffff73fe93f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 5 (Thread 0x7fffde6e3700 (LWP 10508)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x000055555559c58b in cond_wait (c=93824996174048, m=93824996174000) at threading_pthread.c:217
#2  0x00007fffe8e99371 in lfm_thread (ctx=<optimized out>) at lastfm.c:735
#3  0x00007ffff76bb494 in start_thread (arg=0x7fffde6e3700) at pthread_create.c:333
#4  0x00007ffff73fe93f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 4 (Thread 0x7fffdeee4700 (LWP 10507)):
#0  0x00007ffff73ce08d in nanosleep () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007ffff73f79f4 in usleep (useconds=useconds@entry=200000) at ../sysdeps/posix/usleep.c:32
#2  0x00007fffe9372d8f in hotkeys_event_loop (unused=<optimized out>) at hotkeys.c:498
#3  0x00007ffff76bb494 in start_thread (arg=0x7fffdeee4700) at pthread_create.c:333
#4  0x00007ffff73fe93f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 3 (Thread 0x7fffdf6e5700 (LWP 10506)):
#0  pthread_cond_timedwait@@GLIBC_2.3.2 ()
    at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
#1  0x00007fffec5d07af in cache_cleaner_thread (none=<optimized out>) at cache.c:182
#2  0x00007ffff76bb494 in start_thread (arg=0x7fffdf6e5700) at pthread_create.c:333
#3  0x00007ffff73fe93f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 2 (Thread 0x7fffdfee6700 (LWP 10505)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007fffec5d00f1 in fetcher_thread (none=<optimized out>) at artwork.c:1838
#2  0x00007ffff76bb494 in start_thread (arg=0x7fffdfee6700) at pthread_create.c:333
#3  0x00007ffff73fe93f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 1 (Thread 0x7ffff7fb7e80 (LWP 10504)):
#0  0x00007ffff73f54ed in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007ffff474c9f6 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff474cd82 in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff64e4d55 in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#4  0x00007ffff6c2a3ea in gtkui_thread (ctx=ctx@entry=0x0) at gtkui.c:1337
#5  0x00007ffff6c2a64c in gtkui_start () at gtkui.c:1489
#6  0x0000555555588169 in main (argc=<optimized out>, argv=<optimized out>) at main.c:1160
```

I used `git bisect` to find what commit caused that bug. Apparently it's this one:
```
bd2a7486f03f9d2f248b83291a870ba9c96beccf is the first bad commit
commit bd2a7486f03f9d2f248b83291a870ba9c96beccf
Author: Alexey Yakovenko <wakeroid@gmail.com>
Date:   Wed Feb 15 17:03:09 2017 +0100

    pulse: fix compatibility with the new streamer

:040000 040000 a47e98463bd494ad4a60d182b90d45be09677a20 be029ed6e67535ef273616f43524620d3aa367be M	plugins
```

**Comment by Alexey-Yakovenko** [comment]
Should be fixed now.
