### ISSUE TITLE
[wma] Segmentation fault when playing non-existent wma file

### ISSUE THREAD

**Issue by kuba160** [Alexey-Yakovenko/deadbeef#1831]
Steps to reproduce:
1. Add wma file to playlist
2. Delete file from disk or rename file.
3. Play file.

```
Thread 3 "deadbeef-stream" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fd311326700 (LWP 9925)]
stream_track (it=it@entry=0x555555c85540, startpaused=startpaused@entry=0) at streamer.c:1154
1154	        if (new_fileinfo->file) {
(gdb) p new_fileinfo
$1 = (DB_fileinfo_t *) 0x0
```

```
(gdb) bt
#0  stream_track (it=it@entry=0x555555c85540, startpaused=startpaused@entry=0) at streamer.c:1154
#1  0x0000555555598c2a in play_index (startpaused=0, idx=<optimized out>) at streamer.c:1978
#2  streamer_thread (ctx=<optimized out>) at streamer.c:1335
#3  0x00007fd322ed3494 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#4  0x00007fd322c15aff in clone () from /lib/x86_64-linux-gnu/libc.so.6
```

**Comment by Alexey-Yakovenko** [comment]
This doesn't seem to be wma-specific...

**Comment by kuba160** [comment]
I accidentally turned playlist with flac, mp3 and wma files. It always crashed at wma and never at flac or mp3 so I assumed it is wma specific.

**Comment by Alexey-Yakovenko** [comment]
ok funny.. I don't have a single wma file locally
gonna get my old test file collection from another computer, and try it out
